name: Test

pull_request:
  types: [opened, reopened, synchronize]
  branches:
      - main

jobs:
  publish:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run tests
      run: |
        python test.py -v

