name: Unit tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
        - main

jobs:
  publish:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Linter check
      uses: astral-sh/ruff-action@v3
      with:
        src: "./pylan"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        mv misc/unit_test.py tests.py

    - name: Run tests
      run: |
        python tests.py -v

