name: Weekly smoke tests

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
        - main
  # schedule:
  #   - cron: '0 0 * * 1'

jobs:
  publish:
    name: Weekly smoke tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylan-lib
        curl -O https://raw.githubusercontent.com/TimoKats/pylan/refs/heads/cicd/daily-checks/misc/smoke_test.py

    - name: Run tests
      run: |
        python smoke_test.py